//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotoan_AI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cotoan_AI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap d0_v1 {
            get {
                object obj = ResourceManager.GetObject("d0_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d0_v2 {
            get {
                object obj = ResourceManager.GetObject("d0_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d1_v1 {
            get {
                object obj = ResourceManager.GetObject("d1_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d1_v2 {
            get {
                object obj = ResourceManager.GetObject("d1_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d2_v1 {
            get {
                object obj = ResourceManager.GetObject("d2_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d2_v2 {
            get {
                object obj = ResourceManager.GetObject("d2_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d3_v1 {
            get {
                object obj = ResourceManager.GetObject("d3_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d3_v2 {
            get {
                object obj = ResourceManager.GetObject("d3_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d4_v1 {
            get {
                object obj = ResourceManager.GetObject("d4_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d4_v2 {
            get {
                object obj = ResourceManager.GetObject("d4_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d5_v1 {
            get {
                object obj = ResourceManager.GetObject("d5_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d5_v2 {
            get {
                object obj = ResourceManager.GetObject("d5_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d6_v1 {
            get {
                object obj = ResourceManager.GetObject("d6_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d6_v2 {
            get {
                object obj = ResourceManager.GetObject("d6_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d7_v1 {
            get {
                object obj = ResourceManager.GetObject("d7_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d7_v2 {
            get {
                object obj = ResourceManager.GetObject("d7_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d8_v1 {
            get {
                object obj = ResourceManager.GetObject("d8_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d8_v2 {
            get {
                object obj = ResourceManager.GetObject("d8_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d9_v1 {
            get {
                object obj = ResourceManager.GetObject("d9_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap d9_v2 {
            get {
                object obj = ResourceManager.GetObject("d9_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fonts_1_ {
            get {
                object obj = ResourceManager.GetObject("fonts_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fonts_2 {
            get {
                object obj = ResourceManager.GetObject("fonts_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fonts_3 {
            get {
                object obj = ResourceManager.GetObject("fonts_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hl1 {
            get {
                object obj = ResourceManager.GetObject("hl1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hl2 {
            get {
                object obj = ResourceManager.GetObject("hl2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nen1 {
            get {
                object obj = ResourceManager.GetObject("nen1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nen2 {
            get {
                object obj = ResourceManager.GetObject("nen2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nen3 {
            get {
                object obj = ResourceManager.GetObject("nen3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x0_v1 {
            get {
                object obj = ResourceManager.GetObject("x0_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x0_v2 {
            get {
                object obj = ResourceManager.GetObject("x0_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x1_v1 {
            get {
                object obj = ResourceManager.GetObject("x1_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x1_v2 {
            get {
                object obj = ResourceManager.GetObject("x1_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x2_v1 {
            get {
                object obj = ResourceManager.GetObject("x2_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x2_v2 {
            get {
                object obj = ResourceManager.GetObject("x2_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x3_v1 {
            get {
                object obj = ResourceManager.GetObject("x3_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x3_v2 {
            get {
                object obj = ResourceManager.GetObject("x3_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x4_v1 {
            get {
                object obj = ResourceManager.GetObject("x4_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x4_v2 {
            get {
                object obj = ResourceManager.GetObject("x4_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x5_v1 {
            get {
                object obj = ResourceManager.GetObject("x5_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x5_v2 {
            get {
                object obj = ResourceManager.GetObject("x5_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x6_v1 {
            get {
                object obj = ResourceManager.GetObject("x6_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x6_v2 {
            get {
                object obj = ResourceManager.GetObject("x6_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x7_v1 {
            get {
                object obj = ResourceManager.GetObject("x7_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x7_v2 {
            get {
                object obj = ResourceManager.GetObject("x7_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x8_v1 {
            get {
                object obj = ResourceManager.GetObject("x8_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x8_v2 {
            get {
                object obj = ResourceManager.GetObject("x8_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x9_v1 {
            get {
                object obj = ResourceManager.GetObject("x9_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap x9_v2 {
            get {
                object obj = ResourceManager.GetObject("x9_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
